package com.example.callguardian

import android.app.Application
import dagger.hilt.android.HiltAndroidApp
import timber.log.Timber

@HiltAndroidApp
class CallGuardianApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        // BuildConfig is generated by AGP. If it's not found, it might be due to a build error or configuration issue.
        // For now, we can check if the build type is debug using ApplicationInfo flags or just plant the tree.
        // Or we can rely on the fact that Timber.DebugTree() is safe to plant in debug builds.
        
        // A common way to check debuggable without BuildConfig:
        val isDebuggable = (applicationInfo.flags and android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE) != 0
        
        if (isDebuggable && Timber.forest().none { it is Timber.DebugTree }) {
            Timber.plant(Timber.DebugTree())
        }
    }
}
